### ISSUE TITLE
Cannot reproduce the reported results on flicker30k

### ISSUE THREAD

**Issue by fawnliu** [talshaharabany/what-is-where-by-looking#1]
Thanks for your code. I trained the model with VG and then tested it on the flicker30k with the following scripts, and the other settings are kept at their default values.
```
python train_grounding.py \
    -bs 48 \
    -nW 8 \
    -nW_eval 1 \
    -task vg_train \
    -data_path datasets/VG  \
    -val_path  datasets/flicker/ \
```
But I obtained an inferior performance than the one reported in the paper (52 vs. 75.63), and the middle results are shown below:
```
epoches,label,acc
0,test,46.49382716049383
1,test,48.39506172839506
2,test,49.55555555555556
3,test,50.666666666666664
4,test,50.39506172839506
5,test,50.592592592592595
6,test,50.69135802469136
7,test,51.28395061728395
8,test,51.65432098765432
9,test,52.17283950617284
10,test,50.79012345679013
11,test,51.60493827160494
12,test,51.97530864197531
13,test,50.93827160493827
14,test,51.629629629629626
15,test,50.641975308641975
16,test,50.44444444444444
17,test,50.76543209876543
18,test,49.851851851851855
19,test,48.19753086419753
20,test,49.03703703703704
21,test,47.25925925925926
22,test,46.41975308641975
23,test,46.32098765432099
24,test,42.370370370370374
25,test,41.25925925925926
```
Although only 25 epochs were trained, the model achieved worse results at the 25th epoch than the first epoch, and I think the model is probably overfitted. Do I still need to modify other settings to get the same results as in your paper?

**Comment by talshaharabany** [comment]
try this command for faster converges:

python train_grounding.py \
    -bs 48 \
    -nW 8 \
    -nW_eval 1 \
    -task vg_train \
    -data_path datasets/VG  \
    -val_path  datasets/flicker/ \
    -w0 0.25 \
    -w1 4 \
    -w2 0.5 \
    -w3 0.25 \

**Comment by fawnliu** [comment]
Thanks for your prompt reply. I'll try it.
